#!/usr/bin/env bash

set -euo pipefail

function main() {
    if [ "$#" -ne 1 ]; then
        echo Usage: ./getvolume.sh DEVICE
        return 1
    fi

    local device=$1

    local arr=( $(amixer sget "$device" | awk -F "[][]" '/Left:/ { print $4,$2 }') )
    local status=${arr[0]}
    local level=${arr[1]}

    [ "$status" == "on" ] && echo "$level" || echo "off"

    return 0
}

main $@
